Link entrust code with math library
This fixes a linker error "undefined reference to fmodf". It's probably
related to my recent upgrade to CodeSafe 13.3.